// Generated by CoffeeScript 1.9.3
(function() {
  var RabbitMQDataManager, users, uuid, ws;

  ws = require('nodejs-websocket');

  uuid = require('uuid');

  users = [];

  RabbitMQDataManager = null;

  exports.init = function(rabbitMQDataManager) {
    var server;
    RabbitMQDataManager = rabbitMQDataManager;
    return server = ws.createServer(function(conn) {
      var id;
      try {
        console.log("New connection");
        id = uuid.v4();
        conn.on("text", function(str) {
          var e, obj, res;
          console.log("Received " + str);
          try {
            return obj = JSON.parse(str);
          } catch (_error) {
            e = _error;
            res = {
              type: 'other'
            };
            res.login = false;
            res.message = "error on communication";
            return conn.sendText(JSON.stringify(res));
          }
        });
        return conn.on("close", function(code, reason) {
          return console.log("Connection closed");
        });
      } catch (_error) {
        return console.log("error on make a connection");
      }
    }).listen(8001);
  };

}).call(this);
