// Generated by CoffeeScript 1.9.3
(function() {
  var path;

  path = require('path');

  exports.index = function(req, res) {
    return res.sendfile(path.join(__dirname, '../../views/login.html'));
  };

}).call(this);
