// Generated by CoffeeScript 1.10.0
(function() {
  var geoip, path, websocket;

  path = require('path');

  geoip = require('geoip-lite');

  websocket = null;

  exports.init = function(ws) {
    return websocket = ws;
  };

  exports.index = function(req, res) {
    return res.sendfile(path.join(__dirname, '../../views/login.html'));
  };

  exports.main = function(req, res) {
    var geo;
    geo = geoip.lookup(req.connection.remoteAddress);
    console.log(geo);
    if (websocket && req.body && req.body.token) {
      if (websocket.validateToken(req.body.token)) {
        return res.sendfile(path.join(__dirname, '../../views/index.html'));
      } else {
        return res.sendfile(path.join(__dirname, '../../views/login.html'));
      }
    }
  };

  exports.NotificationUsers = function(req, res) {
    var geo;
    geo = geoip.lookup(req.connection.remoteAddress);
    console.log(geo);
    if (websocket && req.body && req.body.token) {
      if (websocket.validateToken(req.body.token)) {
        return res.sendfile(path.join(__dirname, '../../views/NotificationUsers.html'));
      } else {
        return res.sendfile(path.join(__dirname, '../../views/login.html'));
      }
    }
  };

  exports.UserVersionDistribution = function(req, res) {
    if (websocket && req.body && req.body.token) {
      if (websocket.validateToken(req.body.token)) {
        return res.sendfile(path.join(__dirname, '../../views/UserVersionDistribution.html'));
      } else {
        return res.sendfile(path.join(__dirname, '../../views/login.html'));
      }
    }
  };

  exports.RegisteredUsers = function(req, res) {
    if (websocket && req.body && req.body.token) {
      if (websocket.validateToken(req.body.token)) {
        return res.sendfile(path.join(__dirname, '../../views/RegisteredUsers.html'));
      } else {
        return res.sendfile(path.join(__dirname, '../../views/login.html'));
      }
    }
  };

  exports.TaskManager = function(req, res) {
    if (websocket && req.body && req.body.token) {
      if (websocket.validateToken(req.body.token)) {
        return res.sendfile(path.join(__dirname, '../../views/TaskManager.html'));
      } else {
        return res.sendfile(path.join(__dirname, '../../views/login.html'));
      }
    }
  };

  exports.PaidUsers = function(req, res) {
    if (websocket && req.body && req.body.token) {
      if (websocket.validateToken(req.body.token)) {
        return res.sendfile(path.join(__dirname, '../../views/PaidUsers.html'));
      } else {
        return res.sendfile(path.join(__dirname, '../../views/login.html'));
      }
    }
  };

  exports.tt = function(req, res) {
    return res.sendfile(path.join(__dirname, '../../views/index.html'));
  };

}).call(this);
